name: Test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0/2 * * *' # Every two hours

jobs:
  test:
    if: ${{ github.repository == 'nibbleshift/mod2blob' || github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
        check-latest: true
    - name: Test
      run: go test -v

  golangci-lint:
    if: ${{ github.repository == 'nibbleshift/mod2blob' || github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
        check-latest: true
    - name: Lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.57.2
        args: --timeout 30m ./...
